name: Release

on:
  push:
    branches: [master]

jobs:
  release_please:
    name: Prepare release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}

    steps:
      - name: Run Release Please
        id: release
        uses: googleapis/release-please-action@v5
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  publish:
    name: Publish extension
    needs: release_please
    if: needs.release_please.outputs.release_created == 'true'
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - name: Set up pnpm
        uses: Perdolique/automations/.github/actions/setup-pnpm@v3
        with:
          install-dependencies: true

      - name: Test extension
        run: xvfb-run -a pnpm test

      - name: Publish to Visual Studio Marketplace
        run: pnpm exec vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
